### ISSUE TITLE
1.0 release tasks

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#4838]
These are tasks that are blocking for a 1.0 release
- [ ] Updating documentation for all components #4798
- [x] Moving pager to own file #4803
- [x] Removing class directive support for dropdown (BREAKING CHANGE) #4753
- [x] Adding semantic classes to timepicker #4764
- [ ] Implement proper flexible releases for custom script inclusion & compiled copy on npm
- [x] Fix literals in dateparser format #4880
- [x] Implement custom class on all datepicker modes #4873
- [x] Fix carousel being broken in `master` #4972

**Comment by SystemDisc** [comment]
@wesleycho What is "Implement proper flexible releases for custom script inclusion & compiled copy on npm"? Could it use some help?

**Comment by wesleycho** [comment]
It involves some investigation on our side for making a change to our npm releases to point directly to this repository & containing a prebuilt copy of the library to allow users to consume the whole library or to select which components they want to use when using the library via npm.

**Comment by SystemDisc** [comment]
Why not create a "generator" script? I think this would be the easiest approach.

Example: http://expressjs.com/starter/generator.html

**Comment by SystemDisc** [comment]
@wesleycho

**Comment by NicolasVargas** [comment]
Hi !

Any idea about when v1.0 will be out ?

Actually, I'm waiting for the [d859f42](https://github.com/angular-ui/bootstrap/commit/d859f42cc022a5d8779f1c7b358486bbdd04ed57) commit in order to handle typeahead behaviour with min-length === 0.
If v1.0 is not going to be out soon, is there any other solution to get this add/fix ?

Thank you,
Nicolas

**Comment by wesleycho** [comment]
@SystemDisc we can be found in the [Angular Buddies](https://angularbuddies.com/) Slack

@NicolasVargas we are shooting for by the end of the year. Docs contributions for #4798 would help immensely.

**Comment by LeleDev** [comment]
@wesleycho Documentations seems up-to-date now. What about the last missing entry? (Implement proper flexible releases for custom script inclusion & compiled copy on npm)

**Comment by wesleycho** [comment]
We are going to release today - closing this issue due to completion of tasks.
